module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:import/recommended',
  ],
  plugins: ['import', 'simple-import-sort'],
  rules: {
    'arrow-spacing': [2, { 'before': true, 'after': true }],
    'block-spacing': [2, 'always'],
    'eqeqeq': 2,
    'func-call-spacing': 0,
    'import/first': 2,
    'import/no-anonymous-default-export': 2,
    'import/no-deprecated': 2,
    'import/no-duplicates': 2,
    'import/no-empty-named-blocks': 2,
    'import/no-mutable-exports': 2,
    'import/no-named-default': 2,
    'import/no-unused-modules': 1,
    'indent': [2, 'tab', {
      'SwitchCase': 1,
      'VariableDeclarator': 'first',
      'outerIIFEBody': 0,
      'FunctionExpression': { 'parameters': 'first' },
      'CallExpression': { 'arguments': 'first' },
      'ImportDeclaration': 1,
      'offsetTernaryExpressions': true,
      'ignoreComments': true
    }],
    'key-spacing': 2,
    'keyword-spacing': 0,
    'no-lonely-if': 2,
    'no-multiple-empty-lines': [2, { 'max': 2 }],
    'no-restricted-imports': [2, { patterns: ['@/modules/*/*'] }],
    'no-trailing-spaces': 2,
    'no-unneeded-ternary': 2,
    'no-unused-vars': 0,
    'no-useless-escape': 2,
    'no-var': 2,
    'object-shorthand': [2, 'always'],
    'prefer-const': 2,
    'quotes': [2, 'single', { 'avoidEscape': true, 'allowTemplateLiterals': true }],
    'radix': [2, 'as-needed'],
    'react-hooks/exhaustive-deps': 2,
    'react-hooks/rules-of-hooks': 2,
    'simple-import-sort/exports': 2,
    'simple-import-sort/imports': [
      2,
      {
        groups: [
          ['^react', '^@?\\w'],
          [
            '^(@\/components)(/.*|$)',
            '^\\.((?!.(css|scss)).)*$',
          ],
          ['^[^.]'],
        ],
      },
    ],
		'no-console': ['warn', { allow: ['warn', 'error', 'debug'] }],
		'react-hooks/exhaustive-deps': 'error'
  },
};
